### ISSUE TITLE
关于页面统计api的调用问题

### ISSUE THREAD

**Issue by z448401921** [jpush/cordova-plugin-janalytics#2]
您好，我调用页面统计api，极光后台没有显示统计，而自定义事件极光后台都能统计到。不知道是否是调用不成功。代码如下：
![image](https://user-images.githubusercontent.com/9210994/38038251-222526de-32dd-11e8-98e9-9f9b7830ac0c.png)

**Comment by JoshLipan** [comment]
看下log是否有打印报错信息，可以升级到最新版本v1.2.0再试下,注意最新版本开始支持Cordova-Android 7.0.0
