### ISSUE TITLE
ionic4 中报错：ERROR: Plugin 'JAnalyticsPlugin' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.

### ISSUE THREAD

**Issue by gulullu** [jpush/cordova-plugin-janalytics#7]
**ionic4 中报错：**

```
ERROR: Plugin 'JAnalyticsPlugin' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
```

**config.xml 如下配置：**

```
    <plugin name="cordova-plugin-janalytics" spec="1.4.0">
        <variable name="APP_KEY" value="xxxx" />
    </plugin>
```

**调用页面统计事件时报错 ：**

```
AILED pluginJSON = ["INVALID","JAnalyticsPlugin","onPageStart",[{"pageName":"http:\/\/localhost:4989\/app\/tabs\/home"}]]
```

然而手机连上Safari调试时打印**(<any>window).JAnalytics**时是存在的：
![调试](https://i.imgur.com/XatMopX.jpg)

**页面调用方法：**

```
    this.pageName = this.baseService.platform.url();
    if ((<any>window).JAnalytics) {
      (<any>window).JAnalytics.onPageStart({pageName: this.pageName});
    }
```

**Comment by jiguang-official** [comment]
iOS 还是 android 下出现这个问题？

**Comment by huangminlinux** [comment]
iOS 还是 android 下出现这个问题？

**Comment by JoshLipan** [comment]
无后续反馈，关闭

**Comment by jiguang-official** [comment]
尊敬的极光客户：
         你好这个问题你是我们sdk或者插件的问题，请直接搜索Plugin 'JAnalyticsPlugin' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml，找相关报错信息。
你也可以参考这个https://stackoverflow.com/questions/16839110/error-plugin-not-found-or-is-not-a-cdvplugin-check-your-plugin-mapping-in
 
 
 
 
                   如你还有问题可以在极光社区https://community.jiguang.cn/ 搜索你的问题或进行相关问题提问，也可和大家交流互动。



极光开发者平台支持团队
                                                                            
我们希望此回复可以充分解答您的疑问，您也可以在极光社区【https://community.jiguang.cn/】去搜索有没有相关问题及解答。
推荐阅读 JPush 常见问题合集、JMessage 常见问题合集
 
发件人： JoshLipan
发送时间： 2020-06-10 11:52
收件人： jpush/cordova-plugin-janalytics
抄送： jiguang-official; Comment
主题： Re: [jpush/cordova-plugin-janalytics] ionic4 中报错：ERROR: Plugin 'JAnalyticsPlugin' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml. (#7)
无后续反馈，关闭
